### ISSUE TITLE
Sign up warning

### ISSUE THREAD

**Issue by DanielKanyo** [rwieruch/react-firebase-authentication#3]
Hi. Thank you this project, it is awesome. After the registration I get this warning:

Warning: Can only update a mounted or mounting component. This usually means you called setState, replaceState, or forceUpdate on an unmounted component. This is a no-op.

Please check the code for the SignUpForm component.

How can I fix this problem? Thank you.

**Comment by rwieruch** [comment]
It happens when `setState` is called while navigating away from the component where it is called. It's nothing to worry about, but you can checkout [this SO answer](https://stackoverflow.com/questions/48623313/reactdom-unmountcomponentatnode-in-test-causes-warning) to fix it maybe for yourself. 

Thanks for reporting it 👍  I wouldn't want to introduce the fix in this project though, because it complicates things and would make the whole project much more complex for teaching purposes where I use this project :)
